swagger: "2.0"
info:
  description: "API endpoints for partners to send leads to ExactCare staging enviornment"
  version: "1.0.0"
  title: "Web Leads to ExactCare"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "nkopp@exactcarepharmacy.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "staging-exactcare.cs225.force.com"
basePath: "/lead/services/apexrest"
tags:
- name: "Leads"
  description: "Endpoints to send Leads to ExactCare"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /v1/ZipDrugLeadApi/:
    post:
      tags:
      - "ZipDrug Leads"
      summary: "Send Lead"
      description: "send lead to ExactCare"
      operationId: "ZipDrugLead"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Patient object that needs sent to ExactCare"
        required: true
        schema:
          $ref: "#/definitions/Lead"
      responses:
        "405":
          description: "Invalid input"
  /v1/LeadApi/:
    post:
      tags:
      - "Web_Referrer"
      summary: "Send Lead"
      description: "send lead to ExactCare"
      operationId: "sendWebLead"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Patient object that needs sent to ExactCare"
        required: true
        schema:
          $ref: "#/definitions/Web_Referrer"
      responses:
        "405":
          description: "Invalid input"
definitions:
  Lead_Details: 
    type: "object"
    properties: 
      FirstName:
        type: "string"
        example: "John"
      LastName:
        type: "string"
        example: "Smith"
      Gender:
        type: "string"
        example: "male"
      Date_of_Birth:
        type: "string"
      Medical_Record_Number:
        type: "string"
      SSN:
        type: "string"
      Phone: 
        type: "string"
        example: "1234567890"
      MobilePhone:
        type: "string"
        example: "1230456789"
      Street:
        type: "string"
      City: 
        type: "string"
      State:
        type: "string"
      PostalCode:
        type: "string"
      Email: 
        type: "string"
      Primary_Insurance_Id:
        type: "string"
      Status:
        type: "string"
      Discharge_Date:
        type: "string"
      Key_Instructions:
        type: "string"
      Batch_Status:
        type: "string"
      Scheduling_Portal_ID:
        type: "string"
      Scheduling_Portal_GUID:
        type: "string"
      Scheduling_Status:
        type: "string"
      Scheduled_Date_Time:
        type: "string"
      Preferred_Contact_Time:
        type: "string"
      Episode_Id:
        type: "string"
      Source_URL:
        type: "string"
      Patient_IP_Address:
        type: "string"
      Last_External_Communication:
        type: "string"
      Acquired_Date:
        type: "string"
        
  Web_Referrer:
    type: "object"
    properties:
      Referral_Source_System:
        type: "string"
      LeadSource:
        type: "string"
      RecordTypeId:
        type: "string"
      Referral_Source_Details:
        type: "string"
      List_Affiliate_Name:
        type: "string"
      External_Call_Center:
        type: "string"
      Web_Referrer_Source:
        type: "string"
      Web_Referrer_Company:
        type: "string"
      Web_Referrer_Name:
        type: "string"
      Web_Referrer_Phone:
        type: "string"
      Web_Referrer_Email:
        type: "string"
      Referrals:
        type: "array"
        items:
          $ref: "#/definitions/Lead_Details"
        
  Prescription:
        type: "object"
        properties: 
          brand_name:
            type: "string"
            example: "ZOLPIDEM TARTRATE ER"
          generic_name:
            type: "string"
            example: "famotidine"
          days_supply:
            type: "string"
            example: "90"
          ndc_code: 
            type: "string"
            example: "68180077901"
          provider: 
            type: "object"
            properties: 
              full_name: 
                type: "string"
                example: "John Doe"
              npi: 
                type: "string"
                example: "1234567890"
              phone_number: 
                type: "string"
                example: "14158064405"
          pharmacy: 
            type: "object"
            properties: 
              id:
                type: "string"
                example: "515678"
              npi: 
                type: "string"
                example: "9876543210"
              phone_number: 
                type: "string"
                example: "14158064405"
              address: 
                type: "object"
                properties:
                  line1: 
                    type: "string"
                    example: "123 main st"
                  line2: 
                    type: "string"
                    example: "Apt 13q"
                  city:
                    type: "string"
                    example: "New York"
                  postal_code:
                    type: "string"
                    example: "08843"
                  state: 
                    type: "string"
                    example: "NY"
                  note: 
                    type: "string"
                    example: "this is a note"
  Lead:
    type: "object"
    required:
    - "patient_id"
    properties:
      patient_id:
        type: "string"
        example: "1000130447"
      first_name:
        type: "string"
        example: "John"
      last_name:
        type: "string"
        example: "Smith"
      date_of_birth:
        type: "string"
        example: "01/12/1960"
      enroll_status:
        type: "string"
        example: "interested"
      allergies:
        type: "string"
        example: "peanut, soy, wheat"
      address:
        type: "object"
        properties:
          line1: 
            type: "string"
            example: "123 main st"
          line2: 
            type: "string"
            example: "Apt 13q"
          city:
            type: "string"
            example: "New York"
          postal_code:
            type: "string"
            example: "08843"
          state: 
            type: "string"
            example: "NY"
          note: 
            type: "string"
            example: "this is a note"
      prescriptions:
        items:                  
            $ref: "#/definitions/Prescription"
          
    xml:
      name: "Lead"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"